// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzgdpzdztktfchbvivhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6Z2RwemR6dGt0ZmNoYnZpdmhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzU3MTMsImV4cCI6MjA3MDgxMTcxM30.6jCWjuiKsXEPAF33KRdX1b6_Ldx3eieT00ZNknQv6xU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});